version: "3.7"

services:
        flask:
                build: ./flask
                container_name: flask
                restart : always
                environment:
                        - APP_NAME=MySNS
                expose: 
                        - 8080
                volumes:
                        - /home/ubuntu/app/flask:/app

        nginx:
                build: ./nginx
                container_name: nginx 
                restart: always
                ports: 
                        - '80:80'
