FROM python:3.6.8
WORKDIR /app 

COPY requirements.txt /tmp/

RUN pip install -U pip && pip install -r /tmp/requirements.txt && pip install uwsgi && pip install pytz && \
	pip install gevent

CMD ["uwsgi","uwsgi.ini"]

